/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sdmessage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sdmessage.pb-c.h"
void   sdmessage__init
                     (SDMessage         *message)
{
  static const SDMessage init_value = SDMESSAGE__INIT;
  *message = init_value;
}
size_t sdmessage__get_packed_size
                     (const SDMessage *message)
{
  assert(message->base.descriptor == &sdmessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sdmessage__pack
                     (const SDMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sdmessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sdmessage__pack_to_buffer
                     (const SDMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sdmessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SDMessage *
       sdmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SDMessage *)
     protobuf_c_message_unpack (&sdmessage__descriptor,
                                allocator, len, data);
}
void   sdmessage__free_unpacked
                     (SDMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sdmessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue sdmessage__opcode__enum_values_by_number[7] =
{
  { "OP_BAD", "SDMESSAGE__OPCODE__OP_BAD", 0 },
  { "OP_SIZE", "SDMESSAGE__OPCODE__OP_SIZE", 10 },
  { "OP_DEL", "SDMESSAGE__OPCODE__OP_DEL", 20 },
  { "OP_GET", "SDMESSAGE__OPCODE__OP_GET", 30 },
  { "OP_PUT", "SDMESSAGE__OPCODE__OP_PUT", 40 },
  { "OP_GETKEYS", "SDMESSAGE__OPCODE__OP_GETKEYS", 50 },
  { "OP_ERROR", "SDMESSAGE__OPCODE__OP_ERROR", 99 },
};
static const ProtobufCIntRange sdmessage__opcode__value_ranges[] = {
{0, 0},{10, 1},{20, 2},{30, 3},{40, 4},{50, 5},{99, 6},{0, 7}
};
static const ProtobufCEnumValueIndex sdmessage__opcode__enum_values_by_name[7] =
{
  { "OP_BAD", 0 },
  { "OP_DEL", 2 },
  { "OP_ERROR", 6 },
  { "OP_GET", 3 },
  { "OP_GETKEYS", 5 },
  { "OP_PUT", 4 },
  { "OP_SIZE", 1 },
};
const ProtobufCEnumDescriptor sdmessage__opcode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SDMessage.Opcode",
  "Opcode",
  "SDMessage__Opcode",
  "",
  7,
  sdmessage__opcode__enum_values_by_number,
  7,
  sdmessage__opcode__enum_values_by_name,
  7,
  sdmessage__opcode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue sdmessage__c_type__enum_values_by_number[7] =
{
  { "CT_BAD", "SDMESSAGE__C_TYPE__CT_BAD", 0 },
  { "CT_KEY", "SDMESSAGE__C_TYPE__CT_KEY", 10 },
  { "CT_VALUE", "SDMESSAGE__C_TYPE__CT_VALUE", 20 },
  { "CT_ENTRY", "SDMESSAGE__C_TYPE__CT_ENTRY", 30 },
  { "CT_KEYS", "SDMESSAGE__C_TYPE__CT_KEYS", 40 },
  { "CT_RESULT", "SDMESSAGE__C_TYPE__CT_RESULT", 50 },
  { "CT_NONE", "SDMESSAGE__C_TYPE__CT_NONE", 60 },
};
static const ProtobufCIntRange sdmessage__c_type__value_ranges[] = {
{0, 0},{10, 1},{20, 2},{30, 3},{40, 4},{50, 5},{60, 6},{0, 7}
};
static const ProtobufCEnumValueIndex sdmessage__c_type__enum_values_by_name[7] =
{
  { "CT_BAD", 0 },
  { "CT_ENTRY", 3 },
  { "CT_KEY", 1 },
  { "CT_KEYS", 4 },
  { "CT_NONE", 6 },
  { "CT_RESULT", 5 },
  { "CT_VALUE", 2 },
};
const ProtobufCEnumDescriptor sdmessage__c_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SDMessage.C_type",
  "C_type",
  "SDMessage__CType",
  "",
  7,
  sdmessage__c_type__enum_values_by_number,
  7,
  sdmessage__c_type__enum_values_by_name,
  7,
  sdmessage__c_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor sdmessage__field_descriptors[9] =
{
  {
    "opcode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SDMessage, opcode),
    &sdmessage__opcode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "c_type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SDMessage, c_type),
    &sdmessage__c_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_size",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(SDMessage, data_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SDMessage, data),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "result",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(SDMessage, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SDMessage, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "numKeys",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(SDMessage, numkeys),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keys",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(SDMessage, n_keys),
    offsetof(SDMessage, keys),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "op_n",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(SDMessage, op_n),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sdmessage__field_indices_by_name[] = {
  1,   /* field[1] = c_type */
  3,   /* field[3] = data */
  2,   /* field[2] = data_size */
  5,   /* field[5] = key */
  7,   /* field[7] = keys */
  6,   /* field[6] = numKeys */
  8,   /* field[8] = op_n */
  0,   /* field[0] = opcode */
  4,   /* field[4] = result */
};
static const ProtobufCIntRange sdmessage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor sdmessage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SDMessage",
  "SDMessage",
  "SDMessage",
  "",
  sizeof(SDMessage),
  9,
  sdmessage__field_descriptors,
  sdmessage__field_indices_by_name,
  1,  sdmessage__number_ranges,
  (ProtobufCMessageInit) sdmessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
